#!/bin/sh
### BEGIN INIT INFO
# Provides:          gcp-iot-adapter
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       gcp-iot-adapter
### END INIT INFO

VERSION="VER_NUMBER_HERE"
SCRIPT="/opt/gcp-iot-adapter/releases/${VERSION}/amqp_pubsub.sh"
RUNAS=gcpiotadapter

start() {
  echo 'Starting service…' >&2
  local CMD="$SCRIPT start"
  su -c "$CMD" $RUNAS
  echo 'Service started' >&2
}

stop() {
  local CMD="$SCRIPT stop"
  su -c "$CMD" $RUNAS
  echo 'Stopping service…' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
